---
title: "Add Health Figures"
author: "Bernard A. Coles IV"
date: "4/11/2019"
output: pdf_document
---

```{r Loading Data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse)
library(dplyr)
library(gridExtra)
library(grid)
library(rethinking)
library(kableExtra)
library(ggthemes)
library(knitr)
library(broom)

#Mac
load("~/desktop/Repository/Biso/data/wave1.rda")
load("~/desktop/Repository/Biso/data/network.wave1.rda")
load("~/desktop/Repository/Biso/data/weights.rda")

#Renamed
wave1.data <- da21600.0001
network.data <- da21600.0003
weights <- da21600.0004
```

```{r Selecting Variables, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#Merging Relevant Variables into one Data Frame
data1 <- wave1.data %>%
  dplyr :: select(AID, H1FV2, H1FV3, H1FV4, H1FV6, S6A, S6B, S6C, S6D, S6E, S4, S1, S2, PA55, H1FV9)

data2 <-  network.data %>%
  dplyr :: select(AID, ESRDEN, BCENT10X, IDGX2, SEG1RCE5, ERNRC5, EHRC5, AXS59A, AXS59B, AXS59C, AXS59D, AXS59E, AXS59F, AXS59G, SRCE51, SRCE52, SRCE53, SRCE54, SRCE55)

data3 <- weights %>%
  dplyr :: select(AID, GSWGT1)

mydata <- merge(data1, data2, by = "AID") 
#mydata <- merge(my.data, data3, by = "AID")
```

```{r Data Cleaning, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#Race variable
mydata <- mydata %>%
  mutate(race = case_when(
    (S4 == "(1) (1) Yes (go to Q.5)" & S6A == "(1) (1) Marked") ~ "white latino",
    (S4 == "(1) (1) Yes (go to Q.5)" & S6B == "(1) (1) Marked") ~ "black latino",
    (S6A == "(1) (1) Marked" & S6B== "(1) (1) Marked") ~ "mixed race",
    (S6A == "(1) (1) Marked" & S6C == "(1) (1) Marked") ~ "mixed race",
    (S6A == "(1) (1) Marked" & S6D == "(1) (1) Marked") ~ "mixed race",
    (S6A == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    (S6B == "(1) (1) Marked" & S6C == "(1) (1) Marked") ~ "mixed race",
    (S6B == "(1) (1) Marked" & S6D == "(1) (1) Marked") ~ "mixed race",
    (S6B == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    (S6C == "(1) (1) Marked" & S6D == "(1) (1) Marked") ~ "mixed race",
    (S6C == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    (S6D == "(1) (1) Marked" & S6E == "(1) (1) Marked") ~ "mixed race",
    S4 == "(1) (1) Yes (go to Q.5)" ~ "latino", 
    S6A == "(1) (1) Marked" ~ "white",
    S6B == "(1) (1) Marked" ~ "black", 
    S6C == "(1) (1) Marked" ~ "asian", 
    S6D == "(1) (1) Marked" ~ "native american", 
    S6E == "(1) (1) Marked" ~ "other",
    T ~ NA_character_))

#Victimization
mydata <- mydata %>%
  mutate(victim = case_when(
    (H1FV2 == "(1) (1) Once" |  H1FV2 == "(2) (2) More than once") ~ 1,
    (H1FV3 == "(1) (1) Once" |  H1FV3 == "(2) (2) More than once") ~ 1,
    (H1FV4 == "(1) (1) Once" |  H1FV4 == "(2) (2) More than once") ~ 1,
    (H1FV6 == "(1) (1) Once" |  H1FV6 == "(2) (2) More than once") ~ 1,
    H1FV2 == "(0) (0) Never" ~ 0,
    H1FV3 == "(0) (0) Never" ~ 0,
    H1FV4 == "(0) (0) Never" ~ 0,
    H1FV6 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
#Dependent Variable Breakdown Table 
mydata <- mydata %>%
  mutate(knife.gun = case_when(
    (H1FV2 == "(1) (1) Once" |  H1FV2 == "(2) (2) More than once") ~ 1,
    H1FV2 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
mydata <- mydata %>%
  mutate(shot = case_when(
    (H1FV3 == "(1) (1) Once" |  H1FV3 == "(2) (2) More than once") ~ 1,
    H1FV3 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
mydata <- mydata %>%
  mutate(stabbed = case_when(
    (H1FV4 == "(1) (1) Once" |  H1FV4 == "(2) (2) More than once") ~ 1,
    H1FV4 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))
mydata <- mydata %>%
  mutate(jumped = case_when(
    (H1FV6 == "(1) (1) Once" |  H1FV6 == "(2) (2) More than once") ~ 1,
    H1FV6 == "(0) (0) Never" ~ 0,
    T ~ NA_real_))

#Creating the Network Delinquency Variable
mydata <- mydata %>%
  mutate(network.delinquency = (AXS59A + AXS59B + AXS59C + AXS59D + AXS59E + AXS59F + AXS59G)/7) 

#Cleaning Control Variables 
mydata <- mydata %>%
  mutate(female = case_when(
    S2 == "(1) (1) Male" ~ 0,
    S2 == "(2) (2) Female" ~ 1,
    T ~ NA_real_))

mydata$age <- mydata$S1
mydata$family.income <- mydata$PA55


mydata <- mydata %>%
  mutate(weapon.carry = case_when(
    H1FV9 == "(0) (0) None (skip to Q.11)" ~ 0, 
    (H1FV9 == "(1) (1) 1 day" | H1FV9 == "(2) (2) 2 or 3 days" | H1FV9 == "(3) (3) 4 or 5 days" | H1FV9 == "(4) (4) 6 or more days") ~ 1,
    T ~ NA_real_))

#Renaming Network Variables
mydata$racial.heterogeneity <- mydata$ERNRC5
mydata$dense <- mydata$ESRDEN
mydata$centrality <- mydata$BCENT10X
mydata$popularity <- mydata$IDGX2

mydata <- mydata %>%
  mutate(den = case_when(
    (popularity == 0 & centrality == 0) ~ 0,
    T ~ dense))


mydata <- mydata %>%
  mutate(density = den*100)

#Variable Selection 
mydata.dv <- mydata %>%
  select(knife.gun, shot, stabbed, jumped)

mydata <- mydata %>%
  select(AID, victim, race, female, age, family.income, weapon.carry, racial.heterogeneity, network.delinquency, popularity, centrality, density)

#Only complete rows Kept
mydata.c <- mydata[complete.cases(mydata), ]
```

###Plot Practice 
```{r}
race.victim <- mydata.c %>%
  ggplot(aes(x = race)) +
  geom_bar(aes(fill = as.character(victim)), position = "fill") + guides(fill = F) + 
  geom_hline(yintercept= mean(mydata.c$victim), linetype = "dashed", color = "darkred") + #can use annotate() to label the mean line?
  coord_flip() +
  labs(title = "Victimization by Race", y = "Proportion of Victims", x = " ") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), legend.position = "none") 
```

```{r Density Plot}
density <- quantile(mydata.c$density, c(.1, .5, .9))
  
mydata.c <- mydata.c %>%
  mutate(density.cat = case_when(
    density <= 15.7 ~ "0:10th Percentile",
    (density > 15.7 & density <= 26.2) ~ "10th:50th Percentile",
    (density > 26.2 & density <= 50) ~ "50th:90th Percentile",
    density > 50 ~ ">90th Percentile",
    T ~ NA_character_))

density.levels <- c("0:10th Percentile", "10th:50th Percentile", "50th:90th Percentile", ">90th Percentile")

mydata.c <- mydata.c %>%
  mutate(density.cat = factor(density.cat, levels = density.levels, ordered = T))
  
density.weapon <- mydata.c %>%
  ggplot(aes(x = density.cat)) +
  geom_bar(aes(fill = as.character(weapon.carry)), position = "fill") + guides(fill = F) + 
  geom_hline(yintercept= mean(mydata.c$weapon.carry), linetype = "dashed", color = "darkred") + #can use annotate() to label the mean line?
  ylim(0, .1) + 
  annotate("text", x = 3.2, y = 0.063, label = "Mean", color = "darkred") +
  coord_flip() +
  labs(title = "Density", y = "Proportion of Weapon Carriers", x = " ") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), legend.position = "none") 
```

```{r Centrality Plot}
centrality <- quantile(mydata.c$centrality, c(.1, .5, .9))
  
mydata.c <- mydata.c %>%
  mutate(centrality.cat = case_when(
    centrality == 0 ~ "0:10th Percentile",
    (centrality > 0 & centrality <= 0.787) ~ "10th:50th Percentile",
    (centrality > 0.787 & centrality <= 1.702) ~ "50th:90th Percentile",
    centrality > 1.702 ~ ">90th Percentile",
    T ~ NA_character_))

centrality.levels <- c("0:10th Percentile", "10th:50th Percentile", "50th:90th Percentile", ">90th Percentile")

mydata.c <- mydata.c %>%
  mutate(centrality.cat = factor(centrality.cat, levels = centrality.levels, ordered = T))
  
centrality.weapon <- mydata.c %>%
  ggplot(aes(x = centrality.cat)) +
  geom_bar(aes(fill = as.character(weapon.carry)), position = "fill") + guides(fill = F) + 
  geom_hline(yintercept= mean(mydata.c$weapon.carry), linetype = "dashed", color = "darkred") + #can use annotate() to label the mean line?
  ylim(0, .1) + 
  annotate("text", x = 3.2, y = 0.063, label = "Mean", color = "darkred") +
  coord_flip() +
  labs(title = "Centrality", y = "Proportion of Weapon Carriers", x = " ") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), legend.position = "none") 
```

```{r Popularity Plot}
popularity <- quantile(mydata.c$popularity, c(.1, .5, .9))
  
mydata.c <- mydata.c %>%
  mutate(popularity.cat = case_when(
    popularity <= 1 ~ "0:10th Percentile",
    (popularity > 1 & popularity <= 4) ~ "10th:50th Percentile",
    (popularity > 4 & popularity <= 10) ~ "50th:90th Percentile",
    popularity > 10 ~ ">90th Percentile",
    T ~ NA_character_))

popularity <- c("0:10th Percentile", "10th:50th Percentile", "50th:90th Percentile", ">90th Percentile")

mydata.c <- mydata.c %>%
  mutate(popularity.cat = factor(popularity.cat, levels = centrality.levels, ordered = T))
  
popularity.weapon <- mydata.c %>%
  ggplot(aes(x = popularity.cat)) +
  geom_bar(aes(fill = as.character(weapon.carry)), position = "fill") + guides(fill = F) + 
  geom_hline(yintercept= mean(mydata.c$weapon.carry), linetype = "dashed", color = "darkred") + #can use annotate() to label the mean line?
  ylim(0, .1) + 
  annotate("text", x = 3.2, y = 0.063, label = "Mean", color = "darkred") +
  coord_flip() +
  labs(title = "Popularity", y = "Proportion of Weapon Carriers", x = " ") +
  scale_colour_pander() +
  scale_fill_pander() +
  theme_pander() + 
  theme(text = element_text(family = "Times"), plot.title = element_text(hjust = 0.5), legend.position = "none") 
```

```{r}
centrality.weapon
popularity.weapon
density.weapon

a <- grid.arrange(centrality.weapon, popularity.weapon, density.weapon, nrow = 2, ncol = 2)

ggsave("weapons_plot.pdf", a, width = 25, height = 15, units = "cm")
```




















